const letters = [];
letters[0] = ['I', 'F', 'W', 'O', 'N', 'L', 'G'];
letters[1] = ['O', 'D', 'A', 'T', 'H', 'I', 'N'];
letters[2] = ['H', 'C', 'W', 'T', 'I', 'E', 'D'];
letters[3] = ['I', 'A', 'L', 'K', 'E', 'C', 'B'];

const pangrams = [];
pangrams[0] = ['FLOWING', 'FOLLOWING', 'WOLFING'];
pangrams[1] = ['NATIONHOOD'];
pangrams[2] = ['TWITCHED'];
pangrams[3] = ['CLICKABLE'];

const words = [];
words[0] = ['FIFING', 'FILING', 'FILL', 'FILLING', 'FINING', 'FLING', 'FLINGING', 'FLOGGING', 'FOGGING', 'FOIL', 'FOILING', 'FOLIO', 'FOOLING', 'GIGGLING', 'GIGOLO', 'GILL', 'GILLING', 'GINNING', 'GLOWING', 'GOGGLING', 'GOING', 'GOLFING', 'GOOFING', 'GOOGLING', 'GOWNING', 'IGLOO', 'INFILL', 'INFILLING', 'INFLOW', 'INFO', 'INNING', 'LINGO', 'LINING', 'LION', 'LOGGING', 'LOGIN', 'LOIN', 'LOLLING', 'LONGING', 'LOWING', 'NIGGLING', 'NOGGIN', 'NONILLION', 'OFFING', 'OGLING', 'OILING', 'OLIO', 'ONGOING', 'ONION', 'OWING', 'OWNING', 'WIGGING', 'WIGGLING', 'WILL', 'WILLING', 'WILLOW', 'WING', 'WINGING', 'WINING', 'WINNING', 'WINNOW', 'WINNOWING', 'WINO', 'WOOFING', 'WOOING', 'WOWING'];
words[1] = ['ADDITION', 'ANION', 'ANNOTATION', 'ANOINT', 'ANON', 'DHOTI', 'DINO', 'DITTO', 'DODO', 'DONATION', 'DOODAD', 'DOTH', 'HOOD', 'HOODOO', 'HOOT', 'IDIOT', 'INITIATION', 'INTO', 'INTONATION', 'IOTA', 'NATION', 'NOON', 'NOTATION', 'NOTION', 'OATH', 'ONION', 'ONTO', 'TATTOO', 'TOAD', 'TOON', 'TOOT', 'TOOTH'];
words[2] = ['CHEW', 'CHEWED', 'CHIC', 'CHICHI', 'CHIDE', 'CHIDED', 'CHIT', 'DITCH', 'DITCHED', 'ETCH', 'ETCHED', 'ETHIC', 'HECTIC', 'HEED', 'HEEDED', 'HEWED', 'HIDE', 'HIED', 'HITCH', 'HITCHED', 'ITCH', 'ITCHED', 'TECH', 'TECHIE', 'TEETH', 'TEETHE', 'TEETHED', 'THEE', 'TITHE', 'TITHED', 'TWITCH', 'WHEE', 'WHET', 'WHETTED', 'WHEW', 'WHICH', 'WHIT', 'WHITE', 'WIDTH', 'WITCH', 'WITH'];
words[3] = ['ABACI', 'ACACIA', 'ACAI', 'ALIBI', 'ALIKE', 'ALKALI', 'BACILLI', 'BAIL', 'BAILEE', 'BALALAIKA', 'BELIE', 'BIBLE', 'BIBLICAL', 'BIKE', 'BILABIAL', 'BILE', 'BILK', 'BILL', 'BILLABLE', 'CABBIE', 'CELIAC', 'CELLI', 'CILIA', 'CLICK', 'ICICLE', 'ILIAC', 'KIBBLE', 'KICK', 'KICKBACK', 'KICKBALL', 'KILL', 'LABIA', 'LABIAL', 'LABILE', 'LAIC', 'LAICAL', 'LIABLE', 'LIBEL', 'LIBELEE', 'LICE', 'LICK', 'LIKABLE', 'LIKE', 'LIKEABLE', 'LILAC'];

